---
title: "Exploratory data analysis with Rmd"
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 


- TODO

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Use `workflowr` function `wflow_publish()` to publish your website.  
- List the three steps involved in executing a call to `wflow_publish` function  
- Recognize that "publishing" your website synchronizes html files (ie, those outputted from rendering Rmd files) and the source Rmd files. By itself, it doesn't post your site to the internet.       


::::::::::::::::::::::::::::::::::::::::::::::::

```{r, eval = FALSE}
install.packages("palmerpenguins")
```

```{r}
library(palmerpenguins)
data(package = 'palmerpenguins')
head(penguins)
```

```{r}
str(penguins)
```

```{r, eval = FALSE}
# install tidyverse R package
install.packages("tidyverse")
```


```{r}
library(tidyverse)
penguins |> 
  count(species)
penguins |> 
  group_by(species) |> 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))
```


