---
title: "Using RMarkdown"
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 


- TODO

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Use R to install `workflowr` R package on your computer.    
- Use `workflowr` functions in an R session to set up a new project.  


::::::::::::::::::::::::::::::::::::::::::::::::









:::::::::::::::::::::::::::::::::::::: challenge

### What is the directory structure of my new project? 

Where is the file called `about.Rmd`? 

:::::::::::::: solution

### Looking at the directory structure of my project

At a terminal prompt, type:

```
ls -R myproject
```

after replacing "myproject" with the name of your new project.

```
myproject/
├── .gitignore
├── .Rprofile
├── _workflowr.yml
├── analysis/
│   ├── about.Rmd
│   ├── index.Rmd
│   ├── license.Rmd
│   └── _site.yml
├── code/
│   ├── README.md
├── data/
│   └── README.md
├── docs/
├── myproject.Rproj
├── output/
│   └── README.md
└── README.md
```

We see that `about.Rmd` is in the directory `myproject/analysis/`.




:::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::::::::::::::::


* `data/`: This directory is for raw data files.

* `code/`: This directory is for code that might not be appropriate to include
in R Markdown format (e.g. for pre-processing the data, or for long-running
code).

* `output/`: This directory is for processed data files and other
outputs generated from the code and data. For example, scripts in
`code/` that pre-process raw data files from `data/` should save the
processed data files in `output/`.

The `.Rprofile` file is a regular R script that is run once when the project is
opened. It contains the call `library("workflowr")`, ensuring that workflowr is
loaded automatically each time a workflowr-project is opened.




